### PR TITLE
adding ability to preload from cache

### PR DESCRIPTION
**Pull request by iamntg**
as I mentioned in the issue #61 [https://github.com/Templarian/MaterialDesign-Webfont/issues/61],

please do review and merge this

### CODE REVIEW

**Comment by iamntg** [comment]
@Templarian

**Comment by francoism90** [comment]
@iamntg How does this work?

**Comment by tagliala** [comment]
I would avoid this approach because if you rely on the font installed on the system, then icons from new updates will not work

**Comment by Templarian** [comment]
Agreed with all the comments here. Installing the font locally is not something we advise (we actually advise heavily against this).

This is also a distribution repo. https://github.com/Templarian/MaterialDesign-Font-Build Is the repo you want for modification.

**Comment by iamntg** [comment]
I did that mainly for the PWA applications. as per pwa standards, the static files should load from cache first, on the initial load(First Contentful Paint). so, preloading the fonts like that would help. and the service worker can update the font if there is a change.

**Pull request closed without merging**
