### PR TITLE
scss refactoring

### PR DESCRIPTION
**Pull request by pine3ree**

### CODE REVIEW

**Comment by Templarian** [comment]
Just got back from vacation, will be looking through this week. Thanks!

**Comment by pine3ree** [comment]
@Templarian ,
sure, my PR is not related to any issue, just some refactoring (i used a few extra sizes like 16px,32px,64px).
Question: would it be possible to have an alternate _variables.scss file where the original google icons have the original (or better "hypenated") google names?

kind regards

**Comment by Templarian** [comment]
Sorry just remembered to look in this repo (not many make pull requests against it).

Thinking of moving prefixing `$mdi-` to `$sizes` and the others and adding `!default`. That might make it easier for you and others to extend the sizes.

**Comment by pine3ree** [comment]
@Templarian 
That would be helpful to users and the main reason for parametrizing the "size" part of scss.
Even if google recommends those standard sizes, I've found that the "16px" size suits extra-small buttons better and the "32px", "40px" sizes don't look so bad.

kind regards,
maks

**Pull request merged**
