### PR TITLE
:-)

### PR DESCRIPTION
**Pull request by pine3ree**

### CODE REVIEW

**Comment by Templarian** [comment]
How was this not reported as a bug before, guess not many people change the default prefix. Surprised.

Thanks, would have never noticed it since I rarely open that specific file. I'm going to be shooting for a clean `v1.3.0` release in 34 icons. This will go in then.

**Comment by pine3ree** [comment]
@Templarian 
#9 :-)

**Comment by Templarian** [comment]
This made it into `v1.2.65` that was just released.

**Comment by pine3ree** [comment]
oh, thanks! :-)

**Pull request merged**
